name: Publish HCW Docker images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        component:
          - name: admin
            image_name: hcw-admin
            context: ./admin
            version_arg: HCW_ADMIN_VERSION
          - name: backend
            image_name: hcw-backend
            context: ./backend
            version_arg: HCW_BACKEND_VERSION
          - name: doctor
            image_name: hcw-doctor
            context: ./doctor
            version_arg: HCW_DOCTOR_VERSION
          - name: patient
            image_name: hcw-patient
            context: ./patient
            version_arg: HCW_PATIENT_VERSION

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load .env file
        id: dotenv
        uses: falti/dotenv-action@v1.1.2

      - name: Extract metadata (tags, labels) for Docker ${{ matrix.component.name }} v${{ steps.dotenv.outputs.HCW_VERSION }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.component.image_name }}
          tags: |
            type=raw,value=${{ steps.dotenv.outputs.HCW_VERSION }}-${{ env.IMAGE_TAG }}
            type=sha,prefix=${{ steps.dotenv.outputs.HCW_VERSION }}-

      - name: Build and push HCW ${{ matrix.component.name }} v${{ steps.dotenv.outputs.HCW_VERSION }} Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          build-args: |
            ${{ matrix.component.version_arg }}=${{ steps.dotenv.outputs.HCW_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
